### ISSUE TITLE
deps.mak: No such file or directory

### ISSUE THREAD

**Issue by khismatullin** [lukaszcz/pascaladt#1]
steps:

ADT_VERSION=1.0.1
cd ~/Downloads
wget https://codeload.github.com/lukaszcz/pascaladt/tar.gz/refs/tags/v$ADT_VERSION -O pascaladt-$ADT_VERSION.tar.gz
tar xvf pascaladt-$ADT_VERSION.tar.gz
sudo rm -rf pascaladt-$ADT_VERSION.tar.gz
cd pascaladt-$ADT_VERSION
make

logs:

make[1]: Entering directory '/home/khism/Downloads/pascaladt-1.0.1/tools'
cc  -o mktempl mktempl.c
make[1]: cc: No such file or directory
make[1]: *** [Makefile:11: mktempl] Error 127
make[1]: Leaving directory '/home/khism/Downloads/pascaladt-1.0.1/tools'
Makefile:180: deps.mak: No such file or directory
make: *** [Makefile:149: tools.dep] Error 2

**Comment by lukaszcz** [comment]
You need a C compiler as per https://github.com/lukaszcz/pascaladt?tab=readme-ov-file#requirements

The C compiler should be available on the path as `cc` (standard C compiler name on Linux).
